name: inspira
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  cloud_firestore: ^5.4.4
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_unifametro.svg
    - assets/logo_ulabs.svg
    - assets/logo_mude_big.png
    - assets/logo_mude_small.png

  fonts: 
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
